window.tailwind = window.tailwind || {};
window.tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "outline": "#767577",
                "surface-container-low": "#131315",
                "background": "#0e0e10",
                "error-dim": "#d73357",
                "on-secondary-fixed": "#510085",
                "on-tertiary-fixed-variant": "#4d217d",
                "surface-bright": "#2c2c2f",
                "surface-tint": "#b5a0ff",
                "tertiary-fixed": "#cb9cff",
                "on-secondary-fixed-variant": "#7520b5",
                "surface-container-high": "#1f1f22",
                "surface-variant": "#262528",
                "on-tertiary-fixed": "#26004a",
                "secondary": "#c57eff",
                "error": "#ff6e84",
                "on-primary-fixed": "#000000",
                "primary-dim": "#7e51ff",
                "tertiary": "#d3aaff",
                "on-tertiary-container": "#411271",
                "inverse-on-surface": "#555557",
                "tertiary-fixed-dim": "#bd8ff1",
                "primary-fixed-dim": "#9c7eff",
                "on-tertiary": "#4c207c",
                "primary-container": "#a98fff",
                "on-surface": "#f6f3f5",
                "on-background": "#f6f3f5",
                "outline-variant": "#48474a",
                "secondary-fixed": "#e7c5ff",
                "tertiary-dim": "#ba8cee",
                "surface-container-lowest": "#000000",
                "on-primary": "#340090",
                "error-container": "#a70138",
                "surface-container": "#19191c",
                "tertiary-container": "#c899fc",
                "primary": "#b5a0ff",
                "on-primary-fixed-variant": "#32008a",
                "secondary-fixed-dim": "#deb3ff",
                "inverse-surface": "#fcf8fb",
                "on-secondary-container": "#e6c3ff",
                "surface": "#0e0e10",
                "on-surface-variant": "#acaaad",
                "on-error": "#490013",
                "secondary-container": "#6a0baa",
                "on-primary-container": "#280072",
                "surface-container-highest": "#262528",
                "surface-dim": "#0e0e10",
                "primary-fixed": "#a98fff",
                "inverse-primary": "#692cf5",
                "secondary-dim": "#c57eff",
                "on-secondary": "#340058",
                "on-error-container": "#ffb2b9"
            },
            fontFamily: {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
        },
    },
}